name: 04 - Conteneur et IaC
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
env:
  TRIVY: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${{ github.workspace }}:/src -w /src aquasec/trivy:latest
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t sunupay-api:${{ github.sha }} .
      - name: Trivy image (rapport)
        run: $TRIVY image --severity HIGH,CRITICAL --ignore-unfixed --format table --output trivy-image.txt sunupay-api:${{ github.sha }}
      - run: cat trivy-image.txt | head -80
      - name: Trivy image (porte - CRITICAL)
        run: $TRIVY image --severity CRITICAL --ignore-unfixed --exit-code 1 --quiet sunupay-api:${{ github.sha }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rapport-image
          path: trivy-image.txt
  iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy config (Dockerfile + Terraform)
        run: $TRIVY config --severity HIGH,CRITICAL --exit-code 1 .
